name: 'build'

on:
  push:
    branches:
      - master

jobs:
  test-build-ubuntu-2204:
    runs-on: ubuntu-22.04
    env:
      PYTHON_VERSION: 3.11.8
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: bash ${GITHUB_WORKSPACE}/build.sh
  test-build-ubuntu-2404:
    runs-on: ubuntu-24.04
    env:
      PYTHON_VERSION: 3.11.8
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: bash ${GITHUB_WORKSPACE}/build.sh
  test-build-macos-13:
    runs-on: macos-13
    env:
      PYTHON_VERSION: 3.11.8
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: bash ${GITHUB_WORKSPACE}/build.sh
  test-build-macos-14:
    runs-on: macos-14
    env:
      PYTHON_VERSION: 3.11.8
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: bash ${GITHUB_WORKSPACE}/build.sh

