name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build-release:
    strategy:
      matrix:
        include:
          - name: ubuntu-jammy-amd64
            os: ubuntu-22.04
            python_version: '3.10'
            
          - name: ubuntu-noble-amd64
            os: ubuntu-24.04
            python_version: '3.12'
            
          - name: macos-amd64
            os: macos-13
            python_version: '3.10'
            
          - name: macos-arm64
            os: macos-14
            python_version: '3.10'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - run: bash ${GITHUB_WORKSPACE}/build.sh
      - run: tar czf ${{ matrix.name }}-${{ github.ref_name }}.tar.gz -C /usr/local/valet-sh venv
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: |
             ${{ matrix.name }}-${{ github.ref_name }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish-release:
    needs: build-release
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          token: ${{ secrets.GITHUB_TOKEN }}
